FROM node:20 AS ui-builder
WORKDIR /app
COPY web .
RUN npm install && npm run build

FROM golang:1.21 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o generator ./cmd/generator

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/generator .
COPY --from=ui-builder /app/dist ./web/dist
EXPOSE 8080
CMD ["./generator"] 